name: Deploy to Supabase

on:
  push:
    branches:
      - main   # Запускать при каждом пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login $SUPABASE_ACCESS_TOKEN

      - name: Push database migrations
        run: |
          supabase db push

      - name: Deploy functions
        run: |
          supabase functions deploy list-project-members
          supabase functions deploy invite-user || true
          supabase functions deploy accept-invite || true
